<?php

require_once './connect.php';

session_start();

// Set session to expire after 1 day
if (!isset($_SESSION['userid']) || time() - $_SESSION['created'] > 86400) { // 86400 seconds = 24 hours
    session_unset(); // Clear session data
    session_destroy(); // Destroy the session

    // Start a new session for a new user
    session_start();
    $_SESSION['created'] = time();

    // Insert the new user into the database (PostgreSQL generates the UUID and timestamp)
    $sql = "INSERT INTO users (id) VALUES (DEFAULT) RETURNING id";
    $stmt = $pdo->prepare($sql);
    $stmt->execute();

    // Fetch the new UUID generated by PostgreSQL
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    $userId = $row['id'];

    // Store the user ID in the session
    $_SESSION['userid'] = $userId;
} else {
    // Session still valid; keep the existing user ID
    $userId = $_SESSION['userid'];
}
?>