# name: Deploy to EC2 on Push to Main

# on:
#   push:
#     branches:
#       - main # Trigger only on pushes to the main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest # This specifies the runner environment

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.EC2_KEY }}

#       - name: Deploy to EC2
#         env:
#           EC2_HOST: ${{ secrets.EC2_HOST }}
#           EC2_USER: ${{ secrets.EC2_USER }}
#         run: |
#           # Connect to the EC2 instance, fix permissions, and update the web directory
#           ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
#             sudo yum update -y && \
#             sudo yum install -y git && \
#             git config --global --add safe.directory /var/www/html && \
#             sudo chown -R ec2-user:ec2-user /var/www/html && \
#             sudo chmod -R 755 /var/www/html && \
#             cd /var/www/html && \
#             git config pull.rebase false && \
#             git pull origin main
#           '
